definitions:
  main.Event:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
host: https://new-api-events.herokuapp.com/
info:
  contact:
    email: support@swagger.io
    name: API-Event Support
    url: http://www.swagger.io/support
  description: Documentação da API de eventos.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API-Event
  version: "1.0"
paths:
  /events:
    get:
      consumes:
      - application/json
      description: List all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Event'
      summary: Show all events
      tags:
      - events
swagger: "2.0"
